package main

import (
	"log"
	"net/http"

	_ "github.com/davinjaya98/restful_api/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/davinjaya98/restful_api/internal/router"
)

// @title Contacts API
// @version 1.0
// @description This is a sample service for managing contacts
// @termsOfService http://swagger.io/terms/
// @contact.name Davin Jaya Wisastra
// @contact.email davinjayawork@gmail.com
// @host localhost:8080
// @BasePath /
func main() {
	// Start server
	log.Fatal(http.ListenAndServe(":8080", router.InitRouter()))
}